# Generated by Django 3.0.4 on 2020-03-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0004_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='salesforce.Tags'),
        ),
    ]
