# Generated by Django 3.0.4 on 2020-04-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0006_auto_20200326_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
